export const DATA = [
    {
        photo: '/alumni-img/f2019/agnes.jpg',
        name: 'Agnes Totschnig',
        bio: 'Agnes Totschnig is a first year Mathematics student. Besides puzzling over mathematical problems, she is passionate about computer science and theoretical physics. She enjoys hiking in her free time.',
        github: 'https://github.com/atotschnig/Who-s_the_Artist',
    },
    {
        photo: '/alumni-img/f2019/agnes.jpg',
        name: 'Alexander Blostein',
        bio: '',
        github: 'https://github.com/ablost33/Neural-Network-of-Artistic-Style',
    },
    {
        photo: '/alumni-img/f2019/angelica.jpg',
        name: 'Angelica Janevski',
        bio: 'Angelica is a second year computer science major. She likes data science, physics, and 8 hours of sleep.',
        github: 'https://github.com/angelicajanevski/MAIS202-CGAN',
    },
    {
        photo: '/alumni-img/f2019/benjamin.jpg',
        name: 'Benjamin Jiang',
        bio: 'Benjamin Jiang is a second-year Statistics and Computer Science student. In his free time, he likes to play sports.',
        github: 'https://github.com/jiangbenjamin/MAIS-202-Final-Project.git',
    },
    {
        photo: '/alumni-img/f2019/david.jpeg',
        name: 'David Holcer',
        bio: 'David Holcer is an 18 year-old, freshman student studying Mathematics and Computer Science at McGill University. David has pursued his passions throughout highschool, leading a Math Contest Club and participating in the 2015 and 2016 Canada Wide Science Fairs. His scientific research topics have included Kleiber’s Law, Benford’s Law, Nonlinear Optimization, Markov Chains, and Markov Clustering Algorithms for DNA Analysis.',
        github: 'https://github.com/davidholcer/All-The-News-Sentiment-Analysis',
    },
    {
        photo: '/alumni-img/f2019/deepak.jpg',
        name: 'Deepak Singh',
        bio: 'Deepak Singh is a U2 finance student switching into Computer Science. He is interested in FinTech, data science and natural language processing. In his free time, he does Calisthenics and Dragon Boat.',
        github: 'https://github.com/Deepok101/MAIS202_FINAL',
    },
    {
        photo: '/alumni-img/f2019/cole.jpg',
        name: 'Cole Killian',
        bio: "Watch out! Another Statistics and Comp Sci major coming through. His pastimes include finding ways to implement AI into entrepreneurial projects. You'll always find him down for a walk.",
        github: 'https://github.com/Ruborcalor/202mais',
    },
    {
        photo: '/alumni-img/f2019/gohar.jpg',
        name: 'Gohar Saqib Fazal',
        bio: 'Gohar is a 2nd-year electrical engineering student, who has a passion for technical design. He aspires to use machine learning along with his creative thinking skills to develop world-changing and revolutionizing technologies.',
        github: 'https://github.com/goharsaqibfazal/MAIS202_Sign_Language_Translator',
    },
    {
        photo: '/alumni-img/f2019/kelvin.jpg',
        name: 'Kelvin Jin-Yang',
        bio: 'Kelvin is a U3 finance major student. His area of interest lies at the intersection of finance and technology. Outside of the academic fields, he enjoys hiking and badminton.',
        github: 'https://github.com/kelvinjinyang/MAISFinalproject',
    },
    {
        photo: '/alumni-img/f2019/kusha.jpeg',
        name: 'Kusha Sareen',
        bio: 'Kusha is a first year student at McGill University studying Physiology and Mathematics. Although new to the world of AI, Kusha is passionate about learning new things and hopes to apply computer science principles to biology.',
        github: 'https://github.com/kushasareen/mais_final/tree/master',
    },
    {
        photo: '/alumni-img/f2019/lin.jpg',
        name: 'Lin Xiao Zheng',
        bio: 'Lin Xiao is a first year Computer Science student with a strong interest in Mathematics. She enjoys cooking in her free time.',
        github: 'https://github.com/zhenglinxiao/MAIS202_Final_Project',
    },
    {
        photo: '/alumni-img/f2019/michelle.jpg',
        name: 'Michelle Wang',
        bio: 'Michelle is a second year Neuroscience student. Her interests include applying machine learning to the field of neuroscience. She would also like to use knowledge about how the brain learns to help develop artificial intelligence algorithms.',
        github: 'https://github.com/michellewang/grapheme-to-phoneme',
    },
    {
        photo: '/alumni-img/f2019/nadiem.jpg',
        name: 'Nadiem Ahmed',
        bio: 'Nadiem is a third-year Mechanical Engineering student. He’s interested in the application of machine learning to solve business problems and for social good. In his free time, Nadiem likes to play and watch sports.',
        github: 'https://github.com/nadiem99/MAIS202finalproject',
    },
    {
        photo: '/alumni-img/f2019/steve.jpg',
        name: 'Stephen Fay',
        bio: 'Stephen is currently pursuing an undergraduate degree in Mathematics and Physics at McGill University. He enjoys reading, biking, walking, talking, sleeping, problem-solving, and coding. He grew up in Brussels (Belgium) and was a member of the souts et guides pluralistes throughout childhood (and briefly a scout-leader) before moving to Canada.',
        github: 'https://github.com/dcxSt/MAIS202---21cm-ionization-maps-of-the-universe',
    },
    {
        photo: '/alumni-img/f2019/tomer.jpg',
        name: 'Tomer Moran',
        bio: 'Tomer is a math undergrad who loves almost every subject in math, physics, computer science and AI, except for when he is asked to integrate ridiculous functions over ridiculous shapes in his (ridiculous) calculus class. Otherwise, he also likes ultimate frisbee and plays Overwatch in his free time.',
        github: 'https://github.com/Totom3/musical-intelligence',
    },
    {
        photo: '/alumni-img/f2019/xinrui.jpg',
        name: 'Xin Rui Li',
        bio: 'Xin Rui Li is a second-year Software Engineering student minoring in statistics. He’s interested in generative models in machine learning. In his free time, he especially enjoys playing basketball.',
        github: 'https://github.com/xinruili07/MusicGenreClassifier',
    },
    {
        photo: '/alumni-img/f2019/yulu.jpeg',
        name: 'Yu Lu Liu',
        bio: 'Yu Lu is a first-year Statistics and Computer Science student. She’s interested in many fields of machine learning such as sentiment analysis and computer vision. In her free time, she enjoys watching documentaries of deep-sea creatures and rereading her favorite novels.',
        github: 'https://github.com/YuLuLiu/Sarcasm_Detection.git',
    },
    {
        photo: '/alumni-img/f2019/zilong.jpg',
        name: 'Zilong Wang',
        bio: 'Zilong is a U1 Cognitive Science student in COMP stream. He is passionate about state-of-the-art technology and learning new languages, but his current dream is to become a music producer and Youtuber.',
        github: 'https://github.com/mobraine/MAIS-202-Final-Prediction-of-recidivism-model',
    },
];
